Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60

App:
  DefaultPageSize: 10
  MaxPageSize: 100
  DefaultContextTimeout: 60
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: data
  UploadServerUrl: http://127.0.0.1:8080/static
  UploadImageMaxSize: 512  # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
    - .mp4

JWT:
  Secret: eddycjy
  Issuer: blog-service
  Expire: 7200

Database:
  DBType: mysql
  UserName: root
  Password: 12345678
  Host: 127.0.0.1:3306
  DBName: TikTok
  TablePrefix: tiktok_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30