Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60

App:
  DefaultPageSize: 10
  MaxPageSize: 100
  DefaultContextTimeout: 60
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadSavePath: /Users/xuqing/Desktop/upload
  UploadServerUrl: http://10.0.2.2:8080/douyin/video/%s
  UploadImageMaxSize: 512  # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
    - .mp4

JWT:
  Secret: eddycjy
  Issuer: blog-service
  Expire: 7200

Database:
  DBType: mysql
  UserName: root
  Password: 123456
  Host: 127.0.0.1:3306
  DBName: tiktok
  TablePrefix: tiktok_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30

S3Store:
  EndPoint: localhost:9000
  AccessKeyId: minioadmin
  SecretAccessKey: minioadmin
  BucketName: douyin