Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60

App:
  DefaultPageSize: 10
  MaxPageSize: 100
  DefaultContextTimeout: 60
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
  UploadVideoSavePath: storage/uploadsVideo
  UploadImageSavePath: storage/uploadsImage
  UploadVideoServerUrl: http://106.55.103.222:8080/static/video
  UploadImageServerUrl: http://106.55.103.222:8080/static/image
  UploadImageMaxSize: 512  # MB
  UploadImageAllowExts:
    - .jpg
    - .jpeg
    - .png
    - .mp4

JWT:
  Secret: youarebig
  Issuer: tiktok
  Expire: 720000

Database:
  DBType: mysql
  UserName: root
  Password: 12345678
  Host: 127.0.0.1:3306
  DBName: TikTok
  TablePrefix: tiktok_
  Charset: utf8
  ParseTime: True
  MaxIdleConns: 10
  MaxOpenConns: 30
  PrepareStmt: true
  SkipDefaultTransaction: true